### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by joshvazquez** [nstbayless/flyweb-mp3#51]
We should remove remote branches after merging to master so that there is less clutter. Which current branches can be deleted? @nstbayless @wchae @sinoforever

**Comment by nstbayless** [comment]
Thanks @joshvazquez for bringing this up!

I've deleted three branches, which were `issue/20` (#20: delete song from playlist), `add-song` and `playlist-frontend`. These are all topic branches which only I directly contributed to, and they've all long since been merged.

Currently, there is only one branch ahead of master, which is `illegal4` (created by @sinoforever). All other (seven) branches are way behind master (>40 commits) and it doesn't look like there's any reason we should keep them around, but I won't delete them without the consent of the contributors.

**Comment by joshvazquez** [comment]
A bunch of them were mine so I have deleted them.

**Comment by wchae** [comment]
deleted sockets related branches that were already merged

**Comment by nstbayless** [comment]
All branches are now ahead of master (except master :) ) so I'm closing this.
